name = "meteoscope"
compatibility_date = "2026-07-06"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "NOTIFICATIONS_DB"
database_name = "meteoscope-notifications"
database_id = "c1552aac-5617-4ed0-bf69-548a44ef363e"
