// JMA tide-level observation point names.
// Keep these separate from municipality translations: many tide points are
// ports, capes, straits, or local names without an administrative suffix.
export const TIDE_STATION_NAME_TRANSLATIONS = new Map(Object.entries({
  "函館": "Hakodate",
  "小樽": "Otaru",
  "室蘭": "Muroran",
  "釧路": "Kushiro",
  "網走": "Abashiri",
  "留萌": "Rumoi",
  "苫小牧西": "Tomakomai West",
  "稚内": "Wakkanai",
  "紋別": "Monbetsu",
  "根室": "Nemuro",
  "花咲": "Hanasaki",
  "石狩新港": "Ishikari New Port",
  "森": "Mori",
  "江差": "Esashi",
  "奥尻港": "Okushiri Port",
  "瀬棚": "Setana",
  "岩内": "Iwanai",
  "枝幸": "Esashi",
  "沓形": "Kutsugata",
  "白老": "Shiraoi",
  "苫小牧東": "Tomakomai East",
  "浦河": "Urakawa",
  "十勝": "Tokachi",
  "霧多布": "Kiritappu",
  "青森": "Aomori",
  "八戸港": "Hachinohe Port",
  "下北": "Shimokita",
  "竜飛": "Tappi",
  "深浦": "Fukaura",
  "むつ小川原": "Mutsu-Ogawara",
  "宮古": "Miyako",
  "大船渡": "Ofunato",
  "久慈": "Kuji",
  "釜石": "Kamaishi",
  "仙台新港": "Sendai New Port",
  "石巻": "Ishinomaki",
  "鮎川": "Ayukawa",
  "秋田": "Akita",
  "酒田": "Sakata",
  "小名浜": "Onahama",
  "鹿島": "Kashima",
  "銚子漁港": "Choshi Fishing Port",
  "布良": "Mera",
  "千葉": "Chiba",
  "東京": "Tokyo",
  "岡田": "Okada",
  "神津島": "Kozushima",
  "三宅島（坪田）": "Miyakejima (Tsubota)",
  "三宅島（阿古）": "Miyakejima (Ako)",
  "八丈島（神湊）": "Hachijojima (Kaminato)",
  "父島": "Chichijima",
  "京浜港": "Keihin Port",
  "横浜": "Yokohama",
  "横須賀": "Yokosuka",
  "小田原": "Odawara",
  "油壺": "Aburatsubo",
  "新潟東港": "Niigata East Port",
  "新潟西港": "Niigata West Port",
  "上越市直江津（臨時）": "Naoetsu, Joetsu City (temporary)",
  "佐渡": "Sado",
  "粟島": "Awashima",
  "富山": "Toyama",
  "伏木富山": "Fushiki-Toyama",
  "生地": "Ikuji",
  "新湊": "Shinminato",
  "金沢": "Kanazawa",
  "七尾": "Nanao",
  "輪島港": "Wajima Port",
  "珠洲市飯田（臨時）": "Iida, Suzu City (temporary)",
  "能登": "Noto",
  "敦賀": "Tsuruga",
  "清水港": "Shimizu Port",
  "舞阪": "Maisaka",
  "内浦": "Uchiura",
  "下田": "Shimoda",
  "御前崎": "Omaezaki",
  "石廊崎": "Irozaki",
  "名古屋": "Nagoya",
  "三河": "Mikawa",
  "衣浦": "Kinuura",
  "赤羽根": "Akabane",
  "四日市港": "Yokkaichi Port",
  "尾鷲": "Owase",
  "鳥羽": "Toba",
  "熊野": "Kumano",
  "舞鶴": "Maizuru",
  "大阪": "Osaka",
  "淡輪": "Tannowa",
  "神戸": "Kobe",
  "姫路（飾磨）": "Himeji (Shikama)",
  "洲本": "Sumoto",
  "津居山": "Tsuiyama",
  "和歌山": "Wakayama",
  "御坊": "Gobo",
  "白浜": "Shirahama",
  "浦神": "Uragami",
  "串本": "Kushimoto",
  "境": "Sakaiminato",
  "浜田": "Hamada",
  "西郷": "Saigo",
  "三蟠": "Sanban",
  "乙島": "Otoshima",
  "宇野": "Uno",
  "広島": "Hiroshima",
  "呉": "Kure",
  "南風泊": "Haedomari",
  "田ノ首": "Tanokubi",
  "大山の鼻": "Oyama-no-hana",
  "弟子待": "Deshimatsu",
  "長府": "Chofu",
  "宇部": "Ube",
  "徳山": "Tokuyama",
  "小松島": "Komatsushima",
  "阿波由岐": "Awa-Yuki",
  "高松": "Takamatsu",
  "青木": "Aoki",
  "与島": "Yoshima",
  "多度津": "Tadotsu",
  "松山": "Matsuyama",
  "来島航路": "Kurushima Channel",
  "宇和島": "Uwajima",
  "高知": "Kochi",
  "室戸岬": "Muroto Cape",
  "土佐清水": "Tosashimizu",
  "日明": "Hiagari",
  "砂津": "Sunatsu",
  "門司": "Moji",
  "青浜": "Aohama",
  "博多": "Hakata",
  "苅田": "Kanda",
  "唐津": "Karatsu",
  "大浦": "Oura",
  "皇后": "Kogo",
  "長崎": "Nagasaki",
  "佐世保": "Sasebo",
  "平戸瀬戸": "Hirado Strait",
  "厳原": "Izuhara",
  "対馬比田勝": "Hitakatsu, Tsushima",
  "郷ノ浦": "Gonoura",
  "福江": "Fukue",
  "口之津": "Kuchinotsu",
  "熊本": "Kumamoto",
  "八代": "Yatsushiro",
  "本渡瀬戸": "Hondo Strait",
  "苓北": "Reihoku",
  "大分": "Oita",
  "別府": "Beppu",
  "佐伯": "Saiki",
  "宮崎": "Miyazaki",
  "油津": "Aburatsu",
  "鹿児島": "Kagoshima",
  "枕崎": "Makurazaki",
  "西之表": "Nishinoomote",
  "志布志": "Shibushi",
  "奄美": "Amami",
  "名瀬": "Naze",
  "中之島": "Nakanoshima",
  "大泊": "Odomari",
  "種子島": "Tanegashima",
  "那覇": "Naha",
  "石垣": "Ishigaki",
  "中城湾港": "Nakagusuku Bay Port",
  "平良": "Hirara",
  "沖縄": "Okinawa",
  "南大東": "Minamidaito",
  "与那国": "Yonaguni"
}));
