// The monthly catalogue uses the English epicentral-name field.  Keep this
// mapping local so historical search never needs a per-record lookup request.
const NAME_PAIRS = `
ABASHIRI REGION	網走地方
AKAISHI MOUNTAINS REG	赤石山脈
AKINADA SETONAIKAI	安芸灘
AMAKUSA REGION	天草地方
AWAJISHIMA ISLAND REGION	淡路島
BONIN ISLAND REGION	小笠原諸島
BONIN ISLANDS REGION	小笠原諸島
BUNGO CHANNEL	豊後水道
CELEBES SEA	セレベス海
CENTRAL AICHI PREF	愛知県中部
CENTRAL CHIBA PREF	千葉県中部
CENTRAL FUKUI PREF	福井県中部
CENTRAL FUKUOKA PREF	福岡県中部
CENTRAL IZU PENINSULA	伊豆半島中部
CENTRAL NAGANO PREF	長野県中部
CENTRAL SHIZUOKA PREF	静岡県中部
CENTRAL WAKAYAMA PREF	和歌山県中部
CENTRAL YAMANASHI PREF	山梨県中部
E OFF AOMORI PREF	青森県東方沖
E OFF BOSO PENINSULA	房総半島東方沖
E OFF FUKUSHIMA PREF	福島県東方沖
E OFF HACHIJOJIMA ISLAND	八丈島東方沖
E OFF HOKKAIDO	北海道東方沖
E OFF IBARAKI PREF	茨城県東方沖
E OFF IWATE PREF	岩手県東方沖
E OFF IZU PENINSULA	伊豆半島東方沖
E OFF MIYAGI PREF	宮城県東方沖
E OFF TANEGASHIMA ISLAND	種子島東方沖
E PART OF WAKASA BAY	若狭湾東部
EAST CHINA SEA REGION	東シナ海
EAST OF KURIL ISLANDS	千島列島東方沖
EASTERN AOMORI PREF	青森県東部
EASTERN FUKUSHIMA PREF	福島県東部
EASTERN HIROSHIMA PREF	広島県東部
EASTERN NAGANO PREF	長野県東部
EASTERN SAITAMA PREF	埼玉県東部
EASTERN SEA OF JAPAN	日本海東部
EASTERN SHIZUOKA PREF	静岡県東部
EASTERN TOTTORI PREF	鳥取県東部
EASTERN YAMANASHI PREF	山梨県東部
EBINO REGION S KYUSHU	えびの付近
ENSYUNADA	遠州灘
FAR E OFF CENTRAL HONSHU	本州中部東方はるか沖
FAR E OFF FUKUSHIMA PREF	福島県東方はるか沖
FAR E OFF IBARAKI PREF	茨城県東方はるか沖
FAR E OFF IZU ISLANDS	伊豆諸島東方はるか沖
FAR E OFF KANTO	関東東方はるか沖
FAR E OFF MIYAGI PREF	宮城県東方はるか沖
FAR E OFF MIYAZAKI PREF	宮崎県東方はるか沖
FAR E OFF NORTH HONSHU	本州北部東方はるか沖
FAR E OFF OGASAWARA	小笠原諸島東方沖
FAR E OFF SANRIKU	三陸東方はるか沖
FAR FIELD	遠地
FAR S OFF BOSO PENINSULA	房総半島南方はるか沖
FAR S OFF ISHIGAKIJIMA	石垣島南方沖
FAR S OFF OKINAWAJIMA	沖縄本島南方沖
FAR S OFF SHIZUOKA PREF	静岡県南方はるか沖
FAR S OFF TOKAI DISTRICT	東海地方南方はるか沖
FAR SE OFF BOSO PEN	房総半島南東はるか沖
FAR SE OFF HOKKAIDO	北海道南東はるか沖
FAR SE OFF KURILE ISL	千島列島南東沖
FUKUI GIFU BORDER REGION	福井・岐阜県境
GOTO ISLANDS REGION	五島列島近海
HAKONE REGION	箱根付近
HAMANAKO LAKE REGION	浜名湖付近
HARIMANADA SETONAIKAI	播磨灘
HIDA MOUNTAINS REGION	飛騨山脈
HIDAKA MOUNTAINS REGION	日高山脈
HIDAKA REGION	日高地方
HIUCHINADA SETONAIKAI	ひうち灘
HYUGANADA REGION	日向灘
IBURI REGION	胆振地方
IOTO ISLANDS REGION	硫黄島近海
ISE BAY REGION	伊勢湾
ISHIKARI BAY REGION	石狩湾
ISHIKARI DEPRESSION	石狩平野
ISHIKAWA PREF	石川県
IYONADA SETONAIKAI	伊予灘
KAGAWA PREF	香川県
KAMCHATKA	カムチャツカ半島
KAMIKAWA-SORACHI REGION	上川・空知地方
KANAGAWA PREF	神奈川県
KINKAZAN REGION	金華山付近
KUJUKURI COAST BOSO PEN	九十九里沿岸付近
KURIL ISLANDS REGION	千島列島
KURILE ISLANDS REGION	千島列島
KUSHIRO REGION	釧路地方
KYOTO OSAKA BORDER REG	京都・大阪府境
MARIANA ISLANDS REGION	マリアナ諸島
MARIANAS REGION	マリアナ諸島
MID FUKUSHIMA PREF	福島県中部
MID KOCHI PREF	高知県中部
MID KYOTO PREF	京都府中部
MID NIIGATA PREF	新潟県中部
MIKAWA BAY REGION	三河湾
MT. FUJI REGION	富士山付近
N PART OF KII CHANNEL	紀伊水道北部
N PHILIPPINE BASIN	フィリピン海盆北部
NAGASAKI PREF	長崎県
NE AICHI PREF	愛知県北東部
NE EHIME PREF	愛媛県北東部
NE FUKUOKA PREF	福岡県北東部
NE KUMAMOTO PREF	熊本県北東部
NE NIIGATA PREF	新潟県北東部
NE OFF HOKKAIDO	北海道北東沖
NE OFF IWATE PREF	岩手県北東沖
NE SHIMANE PREF	島根県北東部
NE WAKAYAMA PREF	和歌山県北東部
NEAR AMAMI-OSHIMA ISLAND	奄美大島近海
NEAR CHICHIJIMA ISLAND	父島近海
NEAR CHOSHI CITY	銚子付近
NEAR ETOROFU ISLAND	択捉島近海
NEAR HACHIJOJIMA ISLAND	八丈島近海
NEAR ISHIGAKIJIMA ISLAND	石垣島近海
NEAR IZU-OSHIMA ISLAND	伊豆大島近海
NEAR KAGOSHIMA CITY	鹿児島付近
NEAR KAMCHATKA E. COAST	カムチャツカ半島東方沖
NEAR KUNASHIRI ISLAND	国後島近海
NEAR MATSUSHIRO	松代付近
NEAR MINAMI-DAITOJIMA IS	南大東島近海
NEAR MIYAKEJIMA ISLAND	三宅島近海
NEAR MIYAKOJIMA ISLAND	宮古島近海
NEAR NIIJIMA ISLAND	新島近海
NEAR OKINAWAJIMA ISLAND	沖縄本島近海
NEAR TANEGASHIMA ISLAND	種子島近海
NEAR TOKARA ISLANDS	とから列島近海
NEAR TORISHIMA IS	鳥島近海
NEAR UNZENDAKE	雲仙岳付近
NEAR VLADIVOSTOK	ウラジオストク付近
NEMURO REGION	根室地方
NORTH-WEST OF KURILE IS.	千島列島北西沖
NORTHERN AKITA PREF	秋田県北部
NORTHERN ARIAKEKAI REG	有明海北部
NORTHERN CHIBA PREF	千葉県北部
NORTHERN GIFU PREF	岐阜県北部
NORTHERN HYOGO PREF	兵庫県北部
NORTHERN IBARAKI PREF	茨城県北部
NORTHERN IWATE PREF	岩手県北部
NORTHERN KYOTO PREF	京都府北部
NORTHERN MIE PREF	三重県北部
NORTHERN MIYAGI PREF	宮城県北部
NORTHERN MIYAZAKI PREF	宮崎県北部
NORTHERN NAGANO PREF	長野県北部
NORTHERN NARA PREF	奈良県北部
NORTHERN OITA PREF	大分県北部
NORTHERN SURUGA BAY REG	駿河湾北部
NORTHERN TOCHIGI PREF	栃木県北部
NORTHERN YAMAGATA PREF	山形県北部
NOTO PENINSULA REGION	能登半島
NW GUNMA PREF	群馬県北西部
NW KAGOSHIMA PREF	鹿児島県北西部
NW KUMAMOTO PREF	熊本県北西部
NW OFF AMAMI-OSHIMA IS	奄美大島北西沖
NW OFF HOKKAIDO	北海道北西沖
NW OFF HOKURIKU DISTRICT	北陸地方北西沖
NW OFF ISHIGAKIJIMA IS	石垣島北西沖
NW OFF KINKI DISTRICT	近畿地方北西沖
NW OFF KYUSHU	九州地方北西沖
NW OFF MIYAKOJIMA ISLAND	宮古島北西沖
NW OFF OKINAWAJIMA IS	沖縄本島北西沖
NW OFF SHAKOTAN PEN	積丹半島北西沖
NW SHIGA PREF	滋賀県北西部
NW WAKAYAMA PREF	和歌山県北西部
OFF E SAN'IN REGION	山陰地方東部沖
OFF N NIIGATA PREF	新潟県北部沖
OFF NEMURO PENINSULA	根室半島沖
OFF NOTO PENINSULA	能登半島沖
OFF S NIIGATA PREF	新潟県南部沖
OFF W SAN'IN REGION	山陰地方西部沖
OGA PENINSULA REGION	男鹿半島付近
OKAYAMA PREF	岡山県
OKINOSHIMA ISLAND REGION	隠岐島近海
OSAKA BAY REGION	大阪湾
OSAKA PREF	大阪府
OSHIMA PEN REG HOKKAIDO	渡島半島
OSUMI PENINSULA REGION	大隅半島付近
OWASE	尾鷲付近
PHILIPPINE ISL REGION	フィリピン諸島近海
RUMOI REGION	留萌地方
S KOREAN PENINSULA REG	朝鮮半島南部
S OF SURUGA BAY	駿河湾南方沖
S OFF KII PENINSULA	紀伊半島南方沖
S OFF SHIKOKU	四国地方南方沖
S OFF TOMAKOMAI	苫小牧南方沖
S OFF URAKAWA	浦河南方沖
S PART OF KII CHANNEL	紀伊水道南部
SADOGASHIMA IS REG	佐渡島近海
SAGA PREF	佐賀県
SAGAMI BAY REGION	相模湾
SAGAMINADA	相模灘
SATSUMA PENINSULA REGION	薩摩半島付近
SE GIFU PREF	岐阜県南東部
SE GUNMA PREF	群馬県南東部
SE HYOGO PREF	兵庫県南東部
SE KOCHI PREF	高知県南東部
SE OFF BOSO PENINSULA	房総半島南東沖
SE OFF ERIMOMISAKI	襟裳岬南東沖
SE OFF ETOROFU	択捉島南東沖
SE OFF KII PENINSULA	紀伊半島南東沖
SE OFF MIYAGI PREF	宮城県南東沖
SE OFF OSUMI PEN	大隅半島南東沖
SE OFF SHIKOKU	四国地方南東沖
SE OFF TOKACHI	十勝地方南東沖
SE SHIGA PREF	滋賀県南東部
SEA OF JAPAN	日本海
SEA OF OKHOTSK	オホーツク海
SENDAI BAY REGION	仙台湾
SHIGA GIFU BORDER REGION	滋賀・岐阜県境
SHIKOKU BASIN	四国海盆
SHIMA PENINSULA REGION	志摩半島付近
SHIMANE HIROSHIMA BORDER	島根・広島県境
SHIMOKITA PENINSULA REG	下北半島付近
SHIRETOKO PENINSULA REG	知床半島付近
SHIRIBESHI REGION	後志地方
SOUTH OF HONSHU	本州南方沖
SOUTH OF HONSHU, JAPAN	本州南方沖
SOUTH SAKHALIN	サハリン南部
SOUTHERN AKITA PREF	秋田県南部
SOUTHERN BOSO PENINSULA	房総半島南部
SOUTHERN FUKUOKA PREF	福岡県南部
SOUTHERN IBARAKI PREF	茨城県南部
SOUTHERN IWATE PREF	岩手県南部
SOUTHERN IZU PENINSULA	伊豆半島南部
SOUTHERN KUMAMOTO PREF	熊本県南部
SOUTHERN MIE PREF	三重県南部
SOUTHERN MIYAGI PREF	宮城県南部
SOUTHERN MIYAZAKI PREF	宮崎県南部
SOUTHERN NAGANO PREF	長野県南部
SOUTHERN NARA PREF	奈良県南部
SOUTHERN OITA PREF	大分県南部
SOUTHERN SEA OF OKHOTSK	オホーツク海南部
SOUTHERN SIBERIA	シベリア南部
SOUTHERN SURUGA BAY REG	駿河湾南部
SOUTHERN TOCHIGI PREF	栃木県南部
SOUTHERN WAKAYAMA PREF	和歌山県南部
SOUTHERN YAMAGATA PREF	山形県南部
SOYA REGION	宗谷地方
SUONADA SETONAIKAI	周防灘
SW EHIME PREF	愛媛県南西部
SW GIFU PREF	岐阜県南西部
SW HYOGO PREF	兵庫県南西部
SW IBARAKI PREF	茨城県南西部
SW KOCHI PREF	高知県南西部
SW NIIGATA PREF	新潟県南西部
SW OFF HOKKAIDO	北海道南西沖
SW OFF KYUSHU	九州地方南西沖
SW RYUKYU ISLANDS	南西諸島南西沖
SW SHIMANE PREF	島根県南西部
SW SHIZUOKA PREF	静岡県南西部
TAISETSU MOUNTAINS REG	大雪山系
TAIWAN	台湾付近
TAIWAN REGION	台湾付近
TESHIKAGA REGION	弟子屈付近
TOCHIGI GUNMA BORDER	栃木・群馬県境
TOKACHI REGION	十勝地方
TOKUSHIMA PREF	徳島県
TOKYO BAY REGION	東京湾
TOKYO PREF	東京都
TOSA BAY REGION	土佐湾
TOYAMA BAY REGION	富山湾
TOYAMA GIFU BORDER REG	富山・岐阜県境
TOYAMA PREF	富山県
TSUGARU PENINSULA REGION	津軽半島付近
TSUGARU STRAIT REGION	津軽海峡
UCHIURA BAY REGION	内浦湾
VOLCANO IS REGION	火山列島近海
W OFF AKITA PREF	秋田県西方沖
W OFF AMAKUSA ISLAND	天草諸島西方沖
W OFF AOMORI PREF	青森県西方沖
W OFF OGASAWARA	小笠原諸島西方沖
W OFF YAMAGATA PREF	山形県西方沖
W PART OF WAKASA BAY	若狭湾西部
WESTERN AOMORI PREF	青森県西部
WESTERN FUKUI PREF	福井県西部
WESTERN FUKUSHIMA PREF	福島県西部
WESTERN HIROSHIMA PREF	広島県西部
WESTERN NAGANO PREF	長野県西部
WESTERN SAITAMA PREF	埼玉県西部
WESTERN TOTTORI PREF	鳥取県西部
YAMAGUCHI PREF	山口県
YELLOW SEA	黄海
`;

export const HISTORICAL_EPICENTER_NAMES = Object.freeze(Object.fromEntries(
  NAME_PAIRS.trim().split("\n").map((pair) => pair.split("\t", 2))
));

export function translateHistoricalEpicenterName(value) {
  const original = String(value ?? "").trim();
  return HISTORICAL_EPICENTER_NAMES[original] ?? (original || "詳細不明");
}
